"use client";

import Image from "next/image";

/** Reusable PDF header matching the TMU assessment report format */
export function PdfReportHeader({ title, subtitle }: { title: string; subtitle?: string }) {
  return (
    <div style={{ textAlign: "center", marginBottom: "15px", borderBottom: "2px solid #9A1E31", paddingBottom: "10px" }}>
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: "10px", marginBottom: "5px" }}>
        <div style={{ width: "50px", height: "50px", position: "relative" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/tmu-logo.png" alt="TMU Logo" style={{ width: "100%", height: "100%", objectFit: "contain" }} crossOrigin="anonymous" />
        </div>
        <div>
          <h1 style={{ margin: 0, fontSize: "16px", color: "#9A1E31", fontWeight: "900", textTransform: "uppercase" }}>
            Tom Mboya University
          </h1>
          <h2 style={{ margin: 0, fontSize: "12px", color: "#1f2937", fontWeight: "bold" }}>
            {title}
          </h2>
          {subtitle && (
            <p style={{ margin: 0, fontSize: "9px", color: "#64748b" }}>{subtitle}</p>
          )}
        </div>
      </div>
    </div>
  );
}

/** Reusable PDF footer */
export function PdfReportFooter({ generatedBy }: { generatedBy?: string }) {
  const dateFormatted = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  return (
    <div style={{ borderTop: "1px solid #1f2937", marginTop: "30px", paddingTop: "10px", textAlign: "center" }}>
      <span style={{ fontSize: "8px", color: "#4b5563" }}>
        Generated by TMU Teaching Practice System • {dateFormatted} • {generatedBy || "TP Management Platform"} • Confidential
      </span>
      <br />
      <span style={{ fontSize: "7px", color: "#9ca3af" }}>
        This report is system-generated and valid for university records, moderation, and quality assurance.
      </span>
    </div>
  );
}

/** Info block for student/school details grid */
export function PdfInfoBlock({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div style={{ fontSize: "7px", fontWeight: "bold", color: "#64748b", textTransform: "uppercase", marginBottom: "3px" }}>
        {label}
      </div>
      <div style={{ fontSize: "10px", fontWeight: "bold", color: "#1f2937" }}>{value}</div>
    </div>
  );
}

/** Signature block */
export function PdfSignatureBlock({ label }: { label: string }) {
  return (
    <div style={{ textAlign: "center" }}>
      <div style={{ borderBottom: "1px solid #1f2937", marginBottom: "8px", height: "25px" }}></div>
      <div style={{ fontSize: "7px", fontWeight: "bold", color: "#1f2937", textTransform: "uppercase" }}>{label}</div>
    </div>
  );
}

/** PDF download helper using html2pdf.js */
export async function downloadPdf(element: HTMLElement, filename: string) {
  const html2pdf = (await import("html2pdf.js")).default;
  element.classList.remove("hidden");
  const opt = {
    margin: 10,
    filename: `${filename}.pdf`,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true },
    pagebreak: { mode: ["avoid-all", "css", "legacy"] },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" as const },
  };
  await html2pdf().set(opt as any).from(element).save();
  element.classList.add("hidden");
}
