"use client";

import { useRef, useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Download, ArrowLeft, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";

export function AssessmentDetailClient({ assessment }: { assessment: any }) {
  const router = useRouter();
  const pdfRef = useRef<HTMLDivElement>(null);
  const [downloading, setDownloading] = useState(false);
  const [locationName, setLocationName] = useState<string | null>(null);

  // Reverse-geocode submission coordinates to a human-readable location
  useEffect(() => {
    if (assessment.submissionLatitude && assessment.submissionLongitude) {
      fetch(
        `https://nominatim.openstreetmap.org/reverse?lat=${assessment.submissionLatitude}&lon=${assessment.submissionLongitude}&format=json&zoom=16`
      )
        .then((r) => r.json())
        .then((data) => {
          if (data?.display_name) {
            const parts = data.display_name.split(", ");
            setLocationName(parts.slice(0, 4).join(", "));
          }
        })
        .catch(() => setLocationName(null));
    }
  }, [assessment.submissionLatitude, assessment.submissionLongitude]);

  const [isPdf, setIsPdf] = useState(false);

  const handleDownload = async () => {
    if (!pdfRef.current) return;
    setDownloading(true);
    setIsPdf(true);
    
    // Wait for React to render the PDF layout (without DOM headers)
    await new Promise(r => setTimeout(r, 300));
    
    try {
      const html2pdf = (await import("html2pdf.js")).default;
      const studentName = assessment.student.user.name?.replace(/\s+/g, "_") || "Student";
      const refCode = assessment.id.substring(0, 8).toUpperCase();
      
      // Get base64 logo for jsPDF
      const logoImg = document.getElementById("tmu-logo-hidden") as HTMLImageElement;
      let logoDataUrl = "";
      if (logoImg) {
        const canvas = document.createElement("canvas");
        canvas.width = logoImg.naturalWidth;
        canvas.height = logoImg.naturalHeight;
        const ctx = canvas.getContext("2d");
        if (ctx) {
          ctx.drawImage(logoImg, 0, 0);
          logoDataUrl = canvas.toDataURL("image/png");
        }
      }

      const worker = html2pdf()
        .set({
          margin: [38, 10, 15, 10], // top, left, bottom, right
          filename: `TMU_Assessment_${studentName}_${refCode}.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true, letterRendering: true, windowWidth: 1000 },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" as const },
          pagebreak: { mode: ["css", "legacy"] },
        } as any)
        .from(pdfRef.current)
        .toPdf();

      await worker.get('pdf').then((pdf: any) => {
        const totalPages = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          
          // --- HEADER ---
          if (logoDataUrl) {
            pdf.addImage(logoDataUrl, 'PNG', 95, 5, 20, 20); 
          }
          pdf.setFontSize(14);
          pdf.setTextColor(0, 0, 0);
          pdf.setFont("helvetica", "bold");
          pdf.text("TOM MBOYA UNIVERSITY", 105, 30, { align: "center" });
          
          pdf.setFontSize(7);
          pdf.setTextColor(75, 85, 99);
          pdf.setFont("helvetica", "bold");
          pdf.text("Office of the Teaching Practice Coordinator — P.O. Box 199 - 40300, Homa Bay", 105, 34, { align: "center" });
          
          pdf.setDrawColor(154, 30, 49); // #9A1E31
          pdf.setLineWidth(0.5);
          pdf.line(10, 36, 200, 36);
          
          // --- WATERMARK ---
          if (logoDataUrl) {
            pdf.setGState(new (pdf.GState || (window as any).jsPDF.GState)({ opacity: 0.04 }));
            pdf.addImage(logoDataUrl, 'PNG', 45, 88.5, 120, 120);
            pdf.setGState(new (pdf.GState || (window as any).jsPDF.GState)({ opacity: 1.0 }));
          }

          // --- FOOTER ---
          pdf.setDrawColor(31, 41, 55); // #1f2937
          pdf.setLineWidth(0.2);
          pdf.line(10, 285, 200, 285);
          
          pdf.setFontSize(6);
          pdf.setTextColor(75, 85, 99);
          pdf.setFont("helvetica", "normal");
          
          const dateStr = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
          pdf.text(`Generated by Tom Mboya University Teaching Practice System • ${dateStr} • Official Confidential Document • Page ${i} of ${totalPages}`, 105, 289, { align: "center" });
        }
      });
      
      await worker.save();
    } catch (error) {
      console.error("PDF generation failed:", error);
    } finally {
      setIsPdf(false);
      setDownloading(false);
    }
  };

  const dateFormatted = new Date(assessment.createdAt).toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });
  const dateTimeFormatted = new Date(assessment.createdAt).toLocaleString("en-GB", {
    day: "numeric", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit",
  });

  const studentInitials = assessment.student.user.name
    .split(" ")
    .map((n: string) => n[0])
    .join("")
    .substring(0, 2)
    .toUpperCase();

  // Helper component for the repeating header
  const ReportHeader = () => (
    <>
      <div style={{ textAlign: "center", marginBottom: isPdf ? "10px" : "15px" }}>
        <img src="/tmu-logo.png?v=2" alt="TMU Logo" style={{ height: isPdf ? "55px" : "65px", margin: "0 auto", objectFit: "contain" }} />
        <h1 style={{ fontSize: isPdf ? "18px" : "20px", fontWeight: "bold", letterSpacing: "1px", color: "#000000", marginTop: "8px", marginBottom: "4px", textTransform: "uppercase" }}>
          Tom Mboya University
        </h1>
        <p style={{ fontSize: isPdf ? "8px" : "9px", color: "#4b5563", margin: 0, fontWeight: "bold" }}>
          Office of the Teaching Practice Coordinator — P.O. Box 199 - 40300, Homa Bay
        </p>
      </div>
      <div style={{ borderTop: "2px solid #9A1E31", marginBottom: isPdf ? "8px" : "12px" }}></div>
      <div style={{ background: "#faf1f2", padding: isPdf ? "8px" : "12px", textAlign: "center", marginBottom: isPdf ? "15px" : "25px" }}>
        <h2 style={{ fontSize: isPdf ? "12px" : "14px", fontWeight: "bold", color: "#9A1E31", textTransform: "uppercase", letterSpacing: "1px", margin: 0 }}>
          Teaching Practice Assessment Report
        </h2>
        <p style={{ fontSize: isPdf ? "9px" : "11px", fontWeight: "bold", color: "#1f2937", margin: "4px 0 0 0" }}>
          Date of Assessment — {dateFormatted}
        </p>
      </div>
    </>
  );

  return (
    <div className="space-y-6 max-w-5xl mx-auto mb-20">
      <img id="tmu-logo-hidden" src="/tmu-logo.png" alt="" style={{ display: "none" }} crossOrigin="anonymous" />
      
      {/* ── Controls (not in PDF) ── */}
      <div className="flex items-center justify-between">
        <Button variant="ghost" onClick={() => router.back()} className="rounded-xl">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back
        </Button>
        <Button onClick={handleDownload} disabled={downloading} className="bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl shadow-sm gap-2">
          {downloading ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</> : <><Download className="h-4 w-4" /> Download PDF</>}
        </Button>
      </div>

      {/* ── PDF Content ── */}
      <div ref={pdfRef} style={{ background: "#ffffff", color: "#000000", fontFamily: "Arial, sans-serif", padding: isPdf ? "0px" : "40px", borderRadius: isPdf ? "0" : "16px", border: isPdf ? "none" : "1px solid #e2e8f0", boxShadow: isPdf ? "none" : "0 8px 32px rgba(0,0,0,0.06)", position: "relative", overflow: "hidden" }}>
        
        {/* Watermark Logo (Only in web view, jsPDF handles it in PDF) */}
        {!isPdf && (
          <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)", opacity: 0.04, pointerEvents: "none", zIndex: 0 }}>
            <img src="/tmu-logo.png?v=2" alt="" style={{ width: "500px" }} />
          </div>
        )}

        <div style={{ position: "relative", zIndex: 1 }}>
          
          {/* Header (Only in web view, jsPDF handles it in PDF) */}
          {!isPdf && <ReportHeader />}

          {/* Title block (Shown in both) */}
          {isPdf && (
            <div style={{ background: "#faf1f2", padding: "8px", textAlign: "center", marginBottom: "15px" }}>
              <h2 style={{ fontSize: "12px", fontWeight: "bold", color: "#9A1E31", textTransform: "uppercase", letterSpacing: "1px", margin: 0 }}>
                Teaching Practice Assessment Report
              </h2>
              <p style={{ fontSize: "9px", fontWeight: "bold", color: "#1f2937", margin: "4px 0 0 0" }}>
                Date of Assessment — {dateFormatted}
              </p>
            </div>
          )}

          {/* Section 1: Candidate Details */}
          <SectionTitle title="1. CANDIDATE & ASSESSOR DETAILS" isPdf={isPdf} />
          <div style={{ display: "flex", gap: isPdf ? "15px" : "25px", marginBottom: isPdf ? "20px" : "30px", alignItems: "center" }}>
            <div style={{ width: isPdf ? "55px" : "70px", height: isPdf ? "55px" : "70px", border: "2px solid #9A1E31", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <span style={{ fontSize: isPdf ? "20px" : "24px", fontWeight: "bold", color: "#9A1E31" }}>{studentInitials}</span>
            </div>
            <div style={{ flex: 1, display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: isPdf ? "12px" : "20px", borderLeft: "1px solid #e5e7eb", paddingLeft: isPdf ? "15px" : "25px" }}>
              <DataBlock label="CANDIDATE NAME" value={assessment.student.user.name} isPdf={isPdf} />
              <DataBlock label="ADMISSION NUMBER" value={assessment.student.admissionNumber} isPdf={isPdf} />
              <DataBlock label="PROGRAMME / COURSE" value={assessment.student.course} isPdf={isPdf} />
              
              <DataBlock label="ASSESSOR NAME" value={assessment.lecturer.user.name} isPdf={isPdf} />
              <DataBlock label="SCHOOL ATTACHED" value={assessment.student.school?.name || "N/A"} isPdf={isPdf} />
              <DataBlock label="REFERENCE CODE" value={`TP-${assessment.id.substring(0, 8).toUpperCase()}`} isPdf={isPdf} />
            </div>
          </div>

          {/* Section 2: Detailed Rubric */}
          <SectionTitle title="2. DETAILED ASSESSMENT RUBRIC" isPdf={isPdf} />
          <div style={{ border: "1px solid #95a5a6", marginBottom: isPdf ? "20px" : "30px" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "10px" }}>
              <thead>
                <tr style={{ background: "#9A1E31", color: "#ffffff" }}>
                  <th style={{ padding: isPdf ? "4px 8px" : "6px 10px", textAlign: "left", fontWeight: "bold", borderRight: "1px solid #ffffff", width: "30px", fontSize: isPdf ? "9px" : "10px" }}>#</th>
                  <th style={{ padding: isPdf ? "4px 8px" : "6px 10px", textAlign: "left", fontWeight: "bold", borderRight: "1px solid #ffffff", fontSize: isPdf ? "9px" : "10px" }}>ASSESSMENT AREA</th>
                  <th style={{ padding: isPdf ? "4px 8px" : "6px 10px", textAlign: "center", fontWeight: "bold", borderRight: "1px solid #ffffff", width: "80px", fontSize: isPdf ? "9px" : "10px" }}>SCORE</th>
                  <th style={{ padding: isPdf ? "4px 8px" : "6px 10px", textAlign: "center", fontWeight: "bold", width: "80px", fontSize: isPdf ? "9px" : "10px" }}>MAX</th>
                </tr>
              </thead>
              <tbody>
                <GroupHeader title="A. PREPARATION (12 Marks)" isPdf={isPdf} />
                <TableRow index="1" title="Scheme of Work" score={assessment.schemeOfWorkMark} max={2} isPdf={isPdf} />
                <TableRow index="2" title="Lesson Plan: Objectives" score={assessment.lessonPlanObjectives} max={4} isPdf={isPdf} />
                <TableRow index="3" title="Lesson Plan: Activities" score={assessment.lessonPlanActivities} max={2} isPdf={isPdf} />
                <TableRow index="4" title="Lesson Plan: Sequence" score={assessment.lessonPlanSequence} max={4} isPdf={isPdf} />
                
                <GroupHeader title="B. PRESENTATION (80 Marks)" isPdf={isPdf} />
                <SubGroupHeader title="1. Introduction (5 Marks)" isPdf={isPdf} />
                <TableRow index="5" title="Set Induction Skills" score={assessment.introductionMark} max={5} isPdf={isPdf} />
                
                <SubGroupHeader title="2. Lesson Development (30 Marks)" isPdf={isPdf} />
                <TableRow index="6" title="Logical Presentations of Contents" score={assessment.logicalPresentation} max={5} isPdf={isPdf} />
                <TableRow index="7" title="Relevance of Content" score={assessment.contentRelevance} max={5} isPdf={isPdf} />
                <TableRow index="8" title="Adequacy of Content to Time" score={assessment.contentAdequacy} max={5} isPdf={isPdf} />
                <TableRow index="9" title="Teaching Strategies & Methods" score={assessment.teachingStrategies} max={5} isPdf={isPdf} />
                <TableRow index="10" title="Teaching Skills (Motivation, Questioning)" score={assessment.teachingSkills} max={5} isPdf={isPdf} />
                <TableRow index="11" title="Mastery of Content" score={assessment.contentMastery} max={5} isPdf={isPdf} />
                
                <SubGroupHeader title="3. Communication (5 Marks)" isPdf={isPdf} />
                <TableRow index="12" title="Verbal & Non-verbal Communication" score={assessment.communicationMark} max={5} isPdf={isPdf} />
                
                <SubGroupHeader title="4. Resource Materials (15 Marks)" isPdf={isPdf} />
                <TableRow index="13" title="Chalkboard Layout & Use" score={assessment.chalkboardUse} max={3} isPdf={isPdf} />
                <TableRow index="14" title="Timing and Attractiveness" score={assessment.resourceTiming} max={3} isPdf={isPdf} />
                <TableRow index="15" title="Appropriateness" score={assessment.resourceAppropriateness} max={4} isPdf={isPdf} />
                <TableRow index="16" title="Innovativeness & Originality" score={assessment.resourceInnovativeness} max={5} isPdf={isPdf} />
                
                <SubGroupHeader title="5. Classroom Management (20 Marks)" isPdf={isPdf} />
                <TableRow index="17" title="Control and Knowledge of Learners" score={assessment.learnerControl} max={5} isPdf={isPdf} />
                <TableRow index="18" title="Learner Participation" score={assessment.learnerParticipation} max={5} isPdf={isPdf} />
                <TableRow index="19" title="Group Work / Individual Differences" score={assessment.groupWork} max={4} isPdf={isPdf} />
                <TableRow index="20" title="Teacher/Learner Rapport" score={assessment.teacherLearnerRapport} max={5} isPdf={isPdf} />
                
                <SubGroupHeader title="6. Conclusion (5 Marks)" isPdf={isPdf} />
                <TableRow index="21" title="Closure Skills (Review, Questions)" score={assessment.closureSkills} max={2} isPdf={isPdf} />
                <TableRow index="22" title="Concluding Activities (Evaluation)" score={assessment.concludingActivities} max={2} isPdf={isPdf} />
                <TableRow index="23" title="Assignment" score={assessment.assignmentMark} max={1} isPdf={isPdf} />
                
                <GroupHeader title="C. TEACHER PERSONALITY (5 Marks)" isPdf={isPdf} />
                <TableRow index="24" title="Confidence, Dressing, Mannerisms" score={assessment.personalityMark} max={5} isPdf={isPdf} />
                
                <GroupHeader title="D. SELF APPRAISAL (3 Marks)" isPdf={isPdf} />
                <TableRow index="25" title="Use of Previous Comments" score={assessment.selfAppraisalMark} max={3} isPdf={isPdf} />
              </tbody>
            </table>
          </div>

          {/* Section 3: Aggregate Performance */}
          <SectionTitle title="3. AGGREGATE PERFORMANCE" isPdf={isPdf} />
          <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", border: "1px solid #95a5a6", marginBottom: isPdf ? "20px" : "30px" }}>
            <div style={{ padding: isPdf ? "12px" : "16px", textAlign: "center", borderRight: "1px solid #95a5a6" }}>
              <div style={{ fontSize: isPdf ? "8px" : "10px", fontWeight: "bold", color: "#4b5563", textTransform: "uppercase", marginBottom: isPdf ? "4px" : "8px" }}>Total Marks Awarded</div>
              <div style={{ display: "flex", alignItems: "baseline", justifyContent: "center", gap: "2px" }}>
                <span style={{ fontSize: isPdf ? "20px" : "24px", fontWeight: "bold", color: "#9A1E31" }}>{assessment.totalMarks}</span>
                <span style={{ fontSize: isPdf ? "10px" : "12px", fontWeight: "bold", color: "#000000" }}>/100</span>
              </div>
            </div>
            <div style={{ padding: isPdf ? "12px" : "16px", textAlign: "center" }}>
              <div style={{ fontSize: isPdf ? "8px" : "10px", fontWeight: "bold", color: "#4b5563", textTransform: "uppercase", marginBottom: isPdf ? "4px" : "8px" }}>Classification</div>
              <div style={{ fontSize: isPdf ? "14px" : "16px", fontWeight: "bold", color: "#9A1E31", marginTop: isPdf ? "2px" : "6px" }}>{assessment.performanceBand || "Pending"}</div>
            </div>
          </div>

          {/* Section 4: Qualitative Remarks */}
          <SectionTitle title="4. QUALITATIVE REMARKS & VERIFICATION" isPdf={isPdf} />
          <div style={{ marginBottom: isPdf ? "20px" : "35px" }}>
            <RemarkBlock label="AREAS OF STRENGTH" content={assessment.areasOfStrength} isPdf={isPdf} />
            
            <div style={{ border: "1px solid #f3e8ff", background: "#faf5ff", padding: isPdf ? "10px" : "12px 16px", marginBottom: "10px" }}>
              <div style={{ fontSize: isPdf ? "8px" : "9px", fontWeight: "bold", color: "#6b21a8", letterSpacing: "1px", textTransform: "uppercase", marginBottom: "6px" }}>GEOSPATIAL VERIFICATION RECORD</div>
              <div style={{ fontSize: isPdf ? "9px" : "11px", color: "#1f2937", fontStyle: "italic", fontWeight: "bold", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                <div>Date & Time: <span style={{ fontWeight: "normal" }}>{dateTimeFormatted}</span></div>
                <div>Status: <span style={{ fontWeight: "normal", color: assessment.isGeoVerified ? "#059669" : "#d97706" }}>{assessment.isGeoVerified ? "Verified (Inside Radius)" : "Unverified"}</span></div>
                <div style={{ gridColumn: "span 2" }}>Location: <span style={{ fontWeight: "normal" }}>{locationName || (assessment.submissionLatitude ? `${assessment.submissionLatitude.toFixed(5)}, ${assessment.submissionLongitude.toFixed(5)}` : "Not Captured")}</span></div>
                <div style={{ gridColumn: "span 2" }}>System Note: <span style={{ fontWeight: "normal" }}>"{assessment.geoVerificationNote || "N/A"}"</span></div>
              </div>
            </div>
          </div>

          {/* Section 5: Signatures */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "20px", marginTop: isPdf ? "25px" : "40px", marginBottom: isPdf ? "10px" : "0" }}>
            <SignatureBlock label="ASSESSOR's SIGNATURE & DATE" isPdf={isPdf} />
            <SignatureBlock label="CANDIDATE's SIGNATURE & DATE" isPdf={isPdf} />
            <SignatureBlock label="COORDINATOR's SIGNATURE & DATE" isPdf={isPdf} />
          </div>

          {/* Web View Footer (jsPDF handles this in PDF) */}
          {!isPdf && (
            <div style={{ borderTop: "1px solid #1f2937", marginTop: "30px", paddingTop: "10px", textAlign: "center" }}>
              <span style={{ fontSize: "8px", color: "#4b5563" }}>Generated by Tom Mboya University Teaching Practice System • {dateFormatted} • Official Confidential Document</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ── Inline PDF-Safe Subcomponents ── */

function SectionTitle({ title, isPdf }: { title: string, isPdf?: boolean }) {
  return (
    <>
      <h3 style={{ fontSize: isPdf ? "10px" : "12px", color: "#9A1E31", fontWeight: "bold", textTransform: "uppercase", marginBottom: isPdf ? "6px" : "8px", marginTop: isPdf ? "15px" : "25px" }}>
        {title}
      </h3>
      <div style={{ borderTop: "1px solid #cbd5e1", marginBottom: isPdf ? "10px" : "15px" }}></div>
    </>
  );
}

function DataBlock({ label, value, isPdf }: { label: string; value: string, isPdf?: boolean }) {
  return (
    <div>
      <div style={{ fontSize: isPdf ? "7px" : "8px", fontWeight: "bold", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "4px" }}>{label}</div>
      <div style={{ fontSize: isPdf ? "10px" : "12px", fontWeight: "bold", color: "#1f2937" }}>{value}</div>
    </div>
  );
}

function GroupHeader({ title, isPdf }: { title: string, isPdf?: boolean }) {
  return (
    <tr style={{ background: "#f8fafc" }}>
      <td colSpan={4} style={{ padding: isPdf ? "6px 10px" : "8px 12px", color: "#1f2937", fontWeight: "bold", fontSize: isPdf ? "9px" : "11px", borderRight: "1px solid #e5e7eb", borderBottom: "1px solid #e5e7eb" }}>
        {title}
      </td>
    </tr>
  );
}

function SubGroupHeader({ title, isPdf }: { title: string, isPdf?: boolean }) {
  return (
    <tr style={{ background: "#ffffff" }}>
      <td colSpan={4} style={{ padding: isPdf ? "4px 10px 4px 15px" : "6px 12px 6px 20px", color: "#64748b", fontStyle: "italic", fontWeight: "bold", fontSize: isPdf ? "8px" : "10px", borderRight: "1px solid #e5e7eb", borderBottom: "1px dashed #e5e7eb" }}>
        {title}
      </td>
    </tr>
  );
}

function TableRow({ index, title, score, max, isPdf }: { index: string; title: string; score: number; max: number, isPdf?: boolean }) {
  return (
    <tr style={{ borderBottom: "1px solid #e5e7eb" }}>
      <td style={{ padding: isPdf ? "5px 10px" : "8px 12px", color: "#9A1E31", fontWeight: "bold", fontSize: isPdf ? "9px" : "10px", borderRight: "1px solid #e5e7eb" }}>{index}</td>
      <td style={{ padding: isPdf ? "5px 10px" : "8px 12px", color: "#1f2937", fontWeight: "normal", fontSize: isPdf ? "9px" : "10px", borderRight: "1px solid #e5e7eb" }}>{title}</td>
      <td style={{ padding: isPdf ? "5px 10px" : "8px 12px", textAlign: "center", color: "#1f2937", fontSize: isPdf ? "9px" : "10px", borderRight: "1px solid #e5e7eb", fontWeight: "bold" }}>{score}</td>
      <td style={{ padding: isPdf ? "5px 10px" : "8px 12px", textAlign: "center", fontSize: isPdf ? "9px" : "10px", color: "#64748b" }}>{max}</td>
    </tr>
  );
}

function RemarkBlock({ label, content, isPdf }: { label: string; content?: string | null, isPdf?: boolean }) {
  return (
    <div style={{ background: "#f8fafc", padding: isPdf ? "10px" : "12px 16px", marginBottom: isPdf ? "8px" : "10px" }}>
      <div style={{ fontSize: isPdf ? "8px" : "9px", fontWeight: "bold", color: "#64748b", letterSpacing: "1px", textTransform: "uppercase", marginBottom: "6px" }}>{label}</div>
      <div style={{ fontSize: isPdf ? "9px" : "11px", color: "#1f2937", fontStyle: "italic", fontWeight: "bold" }}>"{content || "No specific remarks provided."}"</div>
    </div>
  );
}

function SignatureBlock({ label, isPdf }: { label: string, isPdf?: boolean }) {
  return (
    <div style={{ textAlign: "center" }}>
      <div style={{ borderBottom: "1px solid #1f2937", marginBottom: "8px", height: isPdf ? "25px" : "30px" }}></div>
      <div style={{ fontSize: isPdf ? "7px" : "9px", fontWeight: "bold", color: "#1f2937", textTransform: "uppercase" }}>{label}</div>
    </div>
  );
}
