"use client";

import { useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, ArrowLeft, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";

export function LessonPlanDetailClient({ plan }: { plan: any }) {
  const router = useRouter();
  const pdfRef = useRef<HTMLDivElement>(null);
  const [downloading, setDownloading] = useState(false);
  const [isPdf, setIsPdf] = useState(false);

  const handleDownload = async () => {
    if (!pdfRef.current) return;
    setDownloading(true);
    setIsPdf(true);
    
    // Wait for React to render the PDF layout
    await new Promise(r => setTimeout(r, 300));
    
    try {
      const html2pdf = (await import("html2pdf.js")).default;
      const studentName = plan.student.user.name?.replace(/\s+/g, "_") || "Student";
      const refCode = plan.id.substring(0, 8).toUpperCase();
      
      // Get base64 logo for jsPDF
      const logoImg = document.getElementById("tmu-logo-hidden") as HTMLImageElement;
      let logoDataUrl = "";
      if (logoImg) {
        const canvas = document.createElement("canvas");
        canvas.width = logoImg.naturalWidth;
        canvas.height = logoImg.naturalHeight;
        const ctx = canvas.getContext("2d");
        if (ctx) {
          ctx.drawImage(logoImg, 0, 0);
          logoDataUrl = canvas.toDataURL("image/png");
        }
      }

      const worker = html2pdf()
        .set({
          margin: [38, 10, 15, 10], // top, left, bottom, right
          filename: `TMU_LessonPlan_${studentName}_${refCode}.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true, letterRendering: true, windowWidth: 1000 },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" as const },
          pagebreak: { mode: ["css", "legacy"] },
        } as any)
        .from(pdfRef.current)
        .toPdf();

      await worker.get('pdf').then((pdf: any) => {
        const totalPages = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          
          // --- HEADER ---
          if (logoDataUrl) {
            pdf.addImage(logoDataUrl, 'PNG', 95, 5, 20, 20); 
          }
          pdf.setFontSize(14);
          pdf.setTextColor(0, 0, 0);
          pdf.setFont("helvetica", "bold");
          pdf.text("TOM MBOYA UNIVERSITY", 105, 30, { align: "center" });
          
          pdf.setFontSize(7);
          pdf.setTextColor(75, 85, 99);
          pdf.setFont("helvetica", "bold");
          pdf.text("Office of the Teaching Practice Coordinator — P.O. Box 199 - 40300, Homa Bay", 105, 34, { align: "center" });
          
          pdf.setDrawColor(154, 30, 49); // #9A1E31
          pdf.setLineWidth(0.5);
          pdf.line(10, 36, 200, 36);
          
          // --- WATERMARK ---
          if (logoDataUrl) {
            pdf.setGState(new (pdf.GState || (window as any).jsPDF.GState)({ opacity: 0.04 }));
            pdf.addImage(logoDataUrl, 'PNG', 45, 88.5, 120, 120);
            pdf.setGState(new (pdf.GState || (window as any).jsPDF.GState)({ opacity: 1.0 }));
          }

          // --- FOOTER ---
          pdf.setDrawColor(31, 41, 55); // #1f2937
          pdf.setLineWidth(0.2);
          pdf.line(10, 285, 200, 285);
          
          pdf.setFontSize(6);
          pdf.setTextColor(75, 85, 99);
          pdf.setFont("helvetica", "normal");
          
          const dateStr = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
          pdf.text(`Generated by Tom Mboya University Teaching Practice System • ${dateStr} • Official Confidential Document • Page ${i} of ${totalPages}`, 105, 289, { align: "center" });
        }
      });
      
      await worker.save();
    } catch (error) {
      console.error("PDF generation failed:", error);
    } finally {
      setIsPdf(false);
      setDownloading(false);
    }
  };

  const dateFormatted = new Date(plan.date).toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  const ReportHeader = () => (
    <>
      <div style={{ textAlign: "center", marginBottom: isPdf ? "10px" : "15px" }}>
        <img src="/tmu-logo.png?v=2" alt="TMU Logo" style={{ height: isPdf ? "55px" : "65px", margin: "0 auto", objectFit: "contain" }} />
        <h1 style={{ fontSize: isPdf ? "18px" : "20px", fontWeight: "bold", letterSpacing: "1px", color: "#000000", marginTop: "8px", marginBottom: "4px", textTransform: "uppercase" }}>
          Tom Mboya University
        </h1>
        <p style={{ fontSize: isPdf ? "8px" : "9px", color: "#4b5563", margin: 0, fontWeight: "bold" }}>
          Office of the Teaching Practice Coordinator — P.O. Box 199 - 40300, Homa Bay
        </p>
      </div>
      <div style={{ borderTop: "2px solid #9A1E31", marginBottom: isPdf ? "8px" : "12px" }}></div>
      <div style={{ background: "#faf1f2", padding: isPdf ? "8px" : "12px", textAlign: "center", marginBottom: isPdf ? "15px" : "25px" }}>
        <h2 style={{ fontSize: isPdf ? "12px" : "14px", fontWeight: "bold", color: "#9A1E31", textTransform: "uppercase", letterSpacing: "1px", margin: 0 }}>
          Teaching Practice Lesson Plan
        </h2>
        <p style={{ fontSize: isPdf ? "9px" : "11px", fontWeight: "bold", color: "#1f2937", margin: "4px 0 0 0" }}>
          Lesson Date — {dateFormatted}
        </p>
      </div>
    </>
  );

  return (
    <div className="space-y-6 max-w-5xl mx-auto mb-20">
      <img id="tmu-logo-hidden" src="/tmu-logo.png" alt="" style={{ display: "none" }} crossOrigin="anonymous" />
      
      {/* ── Controls (not in PDF) ── */}
      <div className="flex items-center justify-between no-print mb-6">
        <Button variant="ghost" onClick={() => router.back()} className="rounded-xl">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to Lesson Plans
        </Button>
        <Button onClick={handleDownload} disabled={downloading} className="bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl shadow-sm gap-2">
          {downloading ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</> : <><Download className="h-4 w-4" /> Download PDF</>}
        </Button>
      </div>

      {/* ── PDF Content ── */}
      <div ref={pdfRef} style={{ background: "#ffffff", color: "#000000", fontFamily: "Arial, sans-serif", padding: isPdf ? "0px" : "40px", borderRadius: isPdf ? "0" : "16px", border: isPdf ? "none" : "1px solid #e2e8f0", boxShadow: isPdf ? "none" : "0 8px 32px rgba(0,0,0,0.06)", position: "relative", overflow: "hidden" }}>
        
        {/* Watermark Logo (Only in web view, jsPDF handles it in PDF) */}
        {!isPdf && (
          <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)", opacity: 0.04, pointerEvents: "none", zIndex: 0 }}>
            <img src="/tmu-logo.png?v=2" alt="" style={{ width: "500px" }} />
          </div>
        )}

        <div style={{ position: "relative", zIndex: 1 }}>
          
          {/* Header (Only in web view, jsPDF handles it in PDF) */}
          {!isPdf && <ReportHeader />}

          {/* Title block (Shown in both) */}
          {isPdf && (
            <div style={{ background: "#faf1f2", padding: "8px", textAlign: "center", marginBottom: "15px" }}>
              <h2 style={{ fontSize: "12px", fontWeight: "bold", color: "#9A1E31", textTransform: "uppercase", letterSpacing: "1px", margin: 0 }}>
                Teaching Practice Lesson Plan
              </h2>
              <p style={{ fontSize: "9px", fontWeight: "bold", color: "#1f2937", margin: "4px 0 0 0" }}>
                Lesson Date — {dateFormatted}
              </p>
            </div>
          )}

          {/* Basic Info Table */}
          <table style={{ width: "100%", fontSize: isPdf ? "9px" : "12px", marginBottom: isPdf ? "15px" : "24px", borderCollapse: "collapse" }}>
            <tbody>
              <tr>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc", width: "25%" }}>Name of Teacher</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", width: "25%" }}>{plan.student.user.name}</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc", width: "25%" }}>School</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", width: "25%" }}>{plan.student.school?.name || "N/A"}</td>
              </tr>
              <tr>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc" }}>Subject</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px" }}>{plan.subject}</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc" }}>Class / Form</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px" }}>{plan.classForm} {plan.stream ? `(${plan.stream})` : ""}</td>
              </tr>
              <tr>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc" }}>Topic</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px" }}>{plan.topic}</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc" }}>Sub-topic</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px" }}>{plan.subTopic || "N/A"}</td>
              </tr>
              <tr>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc" }}>Date</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px" }}>{dateFormatted}</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px", fontWeight: "bold", background: "#f8fafc" }}>Time & Duration</td>
                <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px 6px" : "8px" }}>{plan.startTime || "-"} to {plan.endTime || "-"} ({plan.duration || "-"})</td>
              </tr>
            </tbody>
          </table>

          {/* Helper Component for Section Headers */}
          <SectionTitle title="1. Lesson Objectives" isPdf={isPdf} />
          <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937", marginBottom: isPdf ? "15px" : "24px" }}>{plan.objectives}</div>

          <SectionTitle title="2. Introduction / Set Induction" isPdf={isPdf} />
          <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937", marginBottom: isPdf ? "15px" : "24px" }}>{plan.introduction}</div>

          <SectionTitle title="3. Lesson Development" isPdf={isPdf} />
          <table style={{ width: "100%", fontSize: isPdf ? "9px" : "11px", marginBottom: isPdf ? "15px" : "24px", borderCollapse: "collapse", border: "1px solid #cbd5e1" }}>
            <thead style={{ background: "#f8fafc" }}>
              <tr>
                <th style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", textAlign: "left", width: "8%" }}>Time</th>
                <th style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", textAlign: "left", width: "35%" }}>Teacher Activity</th>
                <th style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", textAlign: "left", width: "35%" }}>Learner Activity</th>
                <th style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", textAlign: "left", width: "22%" }}>Resources</th>
              </tr>
            </thead>
            <tbody>
              {Array.isArray(plan.developmentSteps) && plan.developmentSteps.map((step: any, idx: number) => (
                <tr key={idx}>
                  <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", fontFamily: "monospace" }}>{step.time}</td>
                  <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", whiteSpace: "pre-wrap" }}>{step.teacherActivity}</td>
                  <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", whiteSpace: "pre-wrap" }}>{step.learnerActivity}</td>
                  <td style={{ border: "1px solid #cbd5e1", padding: isPdf ? "4px" : "8px", whiteSpace: "pre-wrap" }}>{step.resources}</td>
                </tr>
              ))}
              {(!plan.developmentSteps || plan.developmentSteps.length === 0) && (
                <tr>
                  <td colSpan={4} style={{ border: "1px solid #cbd5e1", padding: "16px", textAlign: "center", fontStyle: "italic", color: "#64748b" }}>No lesson steps provided.</td>
                </tr>
              )}
            </tbody>
          </table>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: isPdf ? "15px" : "24px", marginBottom: isPdf ? "15px" : "24px" }}>
            <div>
              <SectionTitle title="4. Teaching Methods" isPdf={isPdf} />
              <ul style={{ paddingLeft: isPdf ? "15px" : "20px", margin: 0, fontSize: isPdf ? "9px" : "12px", color: "#1f2937" }}>
                {plan.methods?.map((m: string) => <li key={m}>{m}</li>)}
                {(!plan.methods || plan.methods.length === 0) && <li style={{ fontStyle: "italic" }}>None specified</li>}
              </ul>
            </div>
            <div>
              <SectionTitle title="5. Teaching/Learning Resources" isPdf={isPdf} />
              <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937" }}>{plan.resources}</div>
            </div>
          </div>

          <SectionTitle title="6. Assessment Methods" isPdf={isPdf} />
          <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937", marginBottom: isPdf ? "15px" : "24px" }}>{plan.assessment || "None specified"}</div>

          <SectionTitle title="7. Conclusion / Summary" isPdf={isPdf} />
          <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937", marginBottom: isPdf ? "15px" : "24px" }}>{plan.conclusion}</div>

          <SectionTitle title="8. Assignment / Homework" isPdf={isPdf} />
          <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937", marginBottom: isPdf ? "15px" : "24px" }}>{plan.assignment || "None"}</div>

          <div style={{ padding: isPdf ? "10px" : "16px", border: "2px solid #cbd5e1", background: "#f8fafc", marginBottom: isPdf ? "15px" : "24px" }}>
            <h3 style={{ fontSize: isPdf ? "10px" : "12px", color: "#1f2937", fontWeight: "bold", textTransform: "uppercase", marginBottom: isPdf ? "4px" : "8px", borderBottom: "1px solid #cbd5e1", paddingBottom: "4px" }}>
              Self Reflection (Post-Lesson)
            </h3>
            <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px", color: "#1f2937" }}>{plan.reflection || "Pending..."}</div>
          </div>

          {plan.reviewComment && (
            <div style={{ padding: isPdf ? "10px" : "16px", border: "1px solid #fecaca", background: "#fef2f2", color: "#7f1d1d", borderRadius: "4px", marginBottom: isPdf ? "15px" : "24px" }}>
              <h3 style={{ fontSize: isPdf ? "10px" : "12px", fontWeight: "bold", textTransform: "uppercase", marginBottom: isPdf ? "4px" : "8px" }}>Supervisor Remarks</h3>
              <div style={{ whiteSpace: "pre-wrap", fontSize: isPdf ? "9px" : "12px" }}>{plan.reviewComment}</div>
            </div>
          )}

          {/* Web View Footer (jsPDF handles this in PDF) */}
          {!isPdf && (
            <div style={{ borderTop: "1px solid #1f2937", marginTop: "30px", paddingTop: "10px", textAlign: "center" }}>
              <span style={{ fontSize: "8px", color: "#4b5563" }}>Generated by Tom Mboya University Teaching Practice System • {dateFormatted} • Official Confidential Document</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function SectionTitle({ title, isPdf }: { title: string, isPdf?: boolean }) {
  return (
    <>
      <h3 style={{ fontSize: isPdf ? "10px" : "12px", color: "#9A1E31", fontWeight: "bold", textTransform: "uppercase", marginBottom: isPdf ? "4px" : "6px", marginTop: isPdf ? "10px" : "15px" }}>
        {title}
      </h3>
      <div style={{ borderTop: "1px solid #cbd5e1", marginBottom: isPdf ? "6px" : "10px" }}></div>
    </>
  );
}
